### ISSUE TITLE
PDX is not loaded if the file path contains a space

### ISSUE THREAD

**Issue by HispidaBytes** [javahacks/odx-commander#41]
A PDX file is not loaded by the extension if its file path contains a space.
No error is provided to the user either; It silently fail

**Comment by HispidaBytes** [comment]
I tried debugging the lsp-server and it crashes here:
`Exception in thread "pool-1-thread-1" java.nio.file.FileSystemNotFoundException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.javahacks.odx.lsp.IndexService.updateProxyIndex(IndexService.java:145)
	at com.javahacks.odx.lsp.IndexService.updateAndWriteProxyIndex(IndexService.java:124)
	at com.javahacks.odx.lsp.IndexService.processIndexLocation(IndexService.java:116)
	at com.javahacks.odx.lsp.IndexService.updateProxyIndex(IndexService.java:93)
	at com.javahacks.odx.lsp.OdxWorkspaceService.lambda$didChangeConfiguration$0(OdxWorkspaceService.java:43)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.nio.file.FileSystemNotFoundException
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at com.javahacks.odx.index.DocumentIndex.loadCategoryWithFallback(DocumentIndex.java:199)
	at com.javahacks.odx.lsp.IndexService.createNewProxy(IndexService.java:185)
	at com.javahacks.odx.lsp.IndexService.getOrCreateProxy(IndexService.java:173)
	at com.javahacks.odx.lsp.IndexService.lambda$updateProxyIndex$0(IndexService.java:144)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
	at java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)`
	
This seems to be caused by a bug in Java 8 and its ZipFileSystemProvider: [JDK-8172846](https://bugs.openjdk.org/browse/JDK-8172846).

If I build the LSP server with JDK 17, the bug does not occur (I did not try anything else, though).

**Comment by javahacks** [comment]
Many thanks for your efforts! I will examine this bug. The best solution so far is installing a more recent Java version on your machine.
